language: java
jdk: "-openjdk11"
branches:
  only:
  - master
before_install:
- pwd
- ls
- openssl aes-256-cbc -K $encrypted_45de953a4a46_key -iv $encrypted_45de953a4a46_iv -in ./src/main/resources/application.properties.enc -out ./src/main/resources/application.properties -d
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$home/.gradle"
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - dev.joongi@gmail.com
