language: java
jdk: "-openjdk11"
branches:
  only:
  - master
before_install:
- sudo apt-get install expect
- expect -v
- openssl aes-256-cbc -K $encrypted_4ce98ce55cf7_key -iv $encrypted_4ce98ce55cf7_iv -in ./src/main/resources/application.properties.enc -out ./src/main/resources/application.properties -d
- chmod +x gradlew
- expect <<EOF
- scp -q -o StrictHostKeyChecking=no -P 1022 -r README.md pi@jungjoongi.iptime.org:~/server/deploy
- expect "password"
- sleep 2
- send "$scp_pwd\r"
- expect eof
- EOF
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$home/.gradle"
before_script:

script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - dev.joongi@gmail.com


