language: java
jdk: "-openjdk11"
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_4ce98ce55cf7_key -iv $encrypted_4ce98ce55cf7_iv -in application.properties.enc -out application.properties -d
- mv application.properties ./src/main/resources
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$home/.gradle"
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - dev.joongi@gmail.com